const CONSTANTS = {
  ON_DRAG_END_SUCCESS: "ON_DRAG_END_SUCCESS ",
  ON_DRAG_TOPIC_END_SUCCESS: "ON_DRAG_TOPIC_END_SUCCESS",
  ON_ADD_TOPIC: "ON_ADD_TOPIC",
  ON_ADD_CARD: "ON_ADD_CARD",
  ON_DRAG_END: "ON_DRAG_END;",
  TOPIC_API_START: "TOPIC_API_START",
  TOPIC_API_SUCCESS: "TOPIC_API_SUCCESS",
  TOPIC_API_FAILURE: "TOPIC_API_FAILURE",
  TOPIC_FETCH_START: "TOPIC_FETCH_START",
  TOPIC_FETCH_SUCCESS: "TOPIC_FETCH_SUCCESS",
  TOPIC_FETCH_FAILURE: "TOPIC_FETCH_FAILURE",
  TOPIC_UPDATE_START: "TOPIC_FETCH_START",
  TOPIC_UPDATE_SUCCESS: "TOPIC_FETCH_SUCCESS",
  TOPIC_UPDATE_FAILURE: "TOPIC_FETCH_FAILURE",
  USER_APICALL_START: "USER_APICALL_START",
  USER_APICALL_SUCCESS: "USER_APICALL_SUCCESS",
  USER_APICALL_FAILURE: "USER_APICALL_FAILURE",
  DELETE_CARD: "DELETE_CARD",
  EDIT_CARD: "EDIT_CARD",
};

export default CONSTANTS;
