export const AUTHORIZE_TWITTER = "AUTHORIZE_TWITTER";
export const DISCONNECT_TWITTER = "DISCONNECT_TWITTER";
export const INITIALIZE_USER = "INITIALIZE_USER";
export const UPDATE_USER = "UPDATE_USER";
